import '@/styles/globals.css';
import { GeistSans } from 'geist/font';
import type { Metadata } from 'next';

import { ThemeProvider } from '@/components/theme-provider';
import { ThemeSwitcher } from '@/components/theme-switcher';
import { ThemeWrapper } from '@/components/theme-wrapper';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='pt-BR' className={GeistSans.className}>
			<body className='min-min-h-screen bg-background'>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<ThemeWrapper>
						<main className='bg-background flex-1'>{children}</main>
					</ThemeWrapper>
					<ThemeSwitcher />
				</ThemeProvider>
			</body>
		</html>
	);
}
