import { Member } from '@/types';

export const tickets = [
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        description: 'A dashboard não está atualizando os dados',
        project: 'projeto 1',
        type: 'feature',
        priority: 'média',
        status: 'concluído',
        file: {
            size: 0,
            type: '',
            name: '',
            lastModified: 0,
        },
        link: '',
        createdBy: 'Renan',
        createdAt: '2021-09-22',
        updatedAt: '2021-09-22',
    },
];

export const members: Member[] = [
    {
        id: '1',
        name: 'Renan Leonel',
        email: 'r@example.com',
        role: 'ADMIN',
        icon: '/avatars/01.png',
    },
    {
        id: '2',
        name: 'Renan Leonel',
        email: 'r@example.com',
        role: 'DEVELOPER',
        icon: '/avatars/01.png',
    },
    {
        id: '3',
        name: 'Renan Leonel',
        email: 'r@example.com',
        role: 'MEMBER',
        icon: '/avatars/01.png',
    },
    {
        id: '4',
        name: 'Renan Leonel',
        email: 'r@example.com',
        role: 'DEVELOPER',
        icon: '/avatars/01.png',
    },
    {
        id: '5',
        name: 'Renan Leonel',
        email: 'r@example.com',
        role: 'MEMBER',
        icon: '/avatars/01.png',
    },
];
