export const tickets = [
    {
        id: 'TICKET-8782',
        title: 'Problemas na Dashboard',
        project: 'Projeto 1',
        status: 'na fila',
        label: 'bug',
        priority: 'média',
    },
    {
        id: 'TICKET-7878',
        title: 'Cliente não consegue acessar o sistema',
        project: 'Projeto 2',
        status: 'em análise',
        label: 'bug',
        priority: 'alta',
    },
    {
        id: 'TICKET-7839',
        title: 'Criar novo componente de gráfico',
        project: 'Projeto 1',
        status: 'em progresso',
        label: 'sugestão',
        priority: 'baixa',
    },
    {
        id: 'TICKET-7839',
        title: 'Redefinir acesso ao aplicativo',
        project: 'Projeto 2',
        status: 'em progresso',
        label: 'bug',
        priority: 'baixa',
    },
    {
        id: 'TICKET-7839',
        title: 'Criar página de ajuda',
        project: 'Projeto 1',
        status: 'em progresso',
        label: 'sugestão',
        priority: 'baixa',
    },
    {
        id: 'TICKET-7839',
        title: 'Refazer o menu de navegação',
        project: 'Projeto 2',
        status: 'em progresso',
        label: 'sugestão',
        priority: 'baixa',
    },
    {
        id: 'TICKET-7839',
        title: 'Refazer o menu de navegação',
        project: 'Projeto 1',
        status: 'em progresso',
        label: 'sugestão',
        priority: 'baixa',
    },
];
